[package]
name = "azimuth-hal-sim"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
publish = false

[dependencies]
azimuth-hal = { path = "../azimuth-hal" }
workspace-hack = { version = "0.1", path = "../workspace-hack" }
