cargo-features = ["per-package-target"]

[package]
name = "azimuth-gui"
version.workspace = true
edition.workspace = true
authors.workspace = true
default-target = "x86_64-unknown-linux-gnu"

[dependencies]
