cargo-features = ["per-package-target"]

[package]
name = "azimuth-gui"
version.workspace = true
edition.workspace = true
authors.workspace = true
publish = false
default-target = "x86_64-unknown-linux-gnu"

[dependencies]
workspace-hack = { version = "0.1", path = "../workspace-hack" }
